# Generated by Django 4.2.15 on 2024-08-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0004_brand4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded', models.IntegerField()),
            ],
        ),
    ]
